HouseholdStandard.seed(
    # 配偶者なし
    { id: 1, marital_status: 0, children_number: 0, expense_revenue_item_id: 2, expense_ratio_to_revenue: 0.3 },
    { id: 2, marital_status: 0, children_number: 0, expense_revenue_item_id: 3, expense_ratio_to_revenue: 0.01 },
    { id: 3, marital_status: 0, children_number: 0, expense_revenue_item_id: 4, expense_ratio_to_revenue: 0.01 },
    { id: 4, marital_status: 0, children_number: 0, expense_revenue_item_id: 5, expense_ratio_to_revenue: 0.01 },
    { id: 5, marital_status: 0, children_number: 0, expense_revenue_item_id: 6, expense_ratio_to_revenue: 0.01 },
    { id: 6, marital_status: 0, children_number: 0, expense_revenue_item_id: 7, expense_ratio_to_revenue: 0 },
    { id: 7, marital_status: 0, children_number: 0, expense_revenue_item_id: 8, expense_ratio_to_revenue: 0.015 },
    { id: 8, marital_status: 0, children_number: 0, expense_revenue_item_id: 9, expense_ratio_to_revenue: 0.2 },
    { id: 9, marital_status: 0, children_number: 0, expense_revenue_item_id: 10, expense_ratio_to_revenue: 0.015 },
    { id: 10, marital_status: 0, children_number: 0, expense_revenue_item_id: 11, expense_ratio_to_revenue: 0.015 },
    { id: 11, marital_status: 0, children_number: 0, expense_revenue_item_id: 12, expense_ratio_to_revenue: 0.01 },
    { id: 12, marital_status: 0, children_number: 0, expense_revenue_item_id: 13, expense_ratio_to_revenue: 0.01 },
    { id: 13, marital_status: 0, children_number: 0, expense_revenue_item_id: 14, expense_ratio_to_revenue: 0.03 },
    { id: 14, marital_status: 0, children_number: 0, expense_revenue_item_id: 15, expense_ratio_to_revenue: 0.03 },
    { id: 15, marital_status: 0, children_number: 0, expense_revenue_item_id: 16, expense_ratio_to_revenue: 0.05 },
    { id: 16, marital_status: 0, children_number: 0, expense_revenue_item_id: 17, expense_ratio_to_revenue: 0.05 },
    { id: 17, marital_status: 0, children_number: 0, expense_revenue_item_id: 18, expense_ratio_to_revenue: 0.05 },
    { id: 18, marital_status: 0, children_number: 0, expense_revenue_item_id: 19, expense_ratio_to_revenue: 0.05 },
    { id: 19, marital_status: 0, children_number: 0, expense_revenue_item_id: 20, expense_ratio_to_revenue: 0.05 },

    # 配偶者あり、子どもなし
    { id: 20, marital_status: 1, children_number: 0, expense_revenue_item_id: 2, expense_ratio_to_revenue: 0.25 },
    { id: 21, marital_status: 1, children_number: 0, expense_revenue_item_id: 3, expense_ratio_to_revenue: 0.01 },
    { id: 22, marital_status: 1, children_number: 0, expense_revenue_item_id: 4, expense_ratio_to_revenue: 0.01 },
    { id: 23, marital_status: 1, children_number: 0, expense_revenue_item_id: 5, expense_ratio_to_revenue: 0.01 },
    { id: 24, marital_status: 1, children_number: 0, expense_revenue_item_id: 6, expense_ratio_to_revenue: 0.01 },
    { id: 25, marital_status: 1, children_number: 0, expense_revenue_item_id: 7, expense_ratio_to_revenue: 0 },
    { id: 26, marital_status: 1, children_number: 0, expense_revenue_item_id: 8, expense_ratio_to_revenue: 0.015 },
    { id: 27, marital_status: 1, children_number: 0, expense_revenue_item_id: 9, expense_ratio_to_revenue: 0.25 },
    { id: 28, marital_status: 1, children_number: 0, expense_revenue_item_id: 10, expense_ratio_to_revenue: 0.015 },
    { id: 29, marital_status: 1, children_number: 0, expense_revenue_item_id: 11, expense_ratio_to_revenue: 0.015 },
    { id: 30, marital_status: 1, children_number: 0, expense_revenue_item_id: 12, expense_ratio_to_revenue: 0.01 },
    { id: 31, marital_status: 1, children_number: 0, expense_revenue_item_id: 13, expense_ratio_to_revenue: 0.01 },
    { id: 32, marital_status: 1, children_number: 0, expense_revenue_item_id: 14, expense_ratio_to_revenue: 0.03 },
    { id: 33, marital_status: 1, children_number: 0, expense_revenue_item_id: 15, expense_ratio_to_revenue: 0.03 },
    { id: 34, marital_status: 1, children_number: 0, expense_revenue_item_id: 16, expense_ratio_to_revenue: 0.05 },
    { id: 35, marital_status: 1, children_number: 0, expense_revenue_item_id: 17, expense_ratio_to_revenue: 0.05 },
    { id: 36, marital_status: 1, children_number: 0, expense_revenue_item_id: 18, expense_ratio_to_revenue: 0.05 },
    { id: 37, marital_status: 1, children_number: 0, expense_revenue_item_id: 19, expense_ratio_to_revenue: 0.05 },
    { id: 38, marital_status: 1, children_number: 0, expense_revenue_item_id: 20, expense_ratio_to_revenue: 0.05 },

    # 配偶者あり、子ども1人
    { id: 39, marital_status: 1, children_number: 1, expense_revenue_item_id: 2, expense_ratio_to_revenue: 0.25 },
    { id: 40, marital_status: 1, children_number: 1, expense_revenue_item_id: 3, expense_ratio_to_revenue: 0.01 },
    { id: 41, marital_status: 1, children_number: 1, expense_revenue_item_id: 4, expense_ratio_to_revenue: 0.01 },
    { id: 42, marital_status: 1, children_number: 1, expense_revenue_item_id: 5, expense_ratio_to_revenue: 0.01 },
    { id: 43, marital_status: 1, children_number: 1, expense_revenue_item_id: 6, expense_ratio_to_revenue: 0.01 },
    { id: 44, marital_status: 1, children_number: 1, expense_revenue_item_id: 7, expense_ratio_to_revenue: 0.05 },
    { id: 45, marital_status: 1, children_number: 1, expense_revenue_item_id: 8, expense_ratio_to_revenue: 0.015 },
    { id: 46, marital_status: 1, children_number: 1, expense_revenue_item_id: 9, expense_ratio_to_revenue: 0.25 },
    { id: 47, marital_status: 1, children_number: 1, expense_revenue_item_id: 10, expense_ratio_to_revenue: 0.015 },
    { id: 48, marital_status: 1, children_number: 1, expense_revenue_item_id: 11, expense_ratio_to_revenue: 0.015 },
    { id: 49, marital_status: 1, children_number: 1, expense_revenue_item_id: 12, expense_ratio_to_revenue: 0.01 },
    { id: 50, marital_status: 1, children_number: 1, expense_revenue_item_id: 13, expense_ratio_to_revenue: 0.01 },
    { id: 51, marital_status: 1, children_number: 1, expense_revenue_item_id: 14, expense_ratio_to_revenue: 0.03 },
    { id: 52, marital_status: 1, children_number: 1, expense_revenue_item_id: 15, expense_ratio_to_revenue: 0.03 },
    { id: 53, marital_status: 1, children_number: 1, expense_revenue_item_id: 16, expense_ratio_to_revenue: 0.05 },
    { id: 54, marital_status: 1, children_number: 1, expense_revenue_item_id: 17, expense_ratio_to_revenue: 0.05 },
    { id: 55, marital_status: 1, children_number: 1, expense_revenue_item_id: 18, expense_ratio_to_revenue: 0.05 },
    { id: 56, marital_status: 1, children_number: 1, expense_revenue_item_id: 19, expense_ratio_to_revenue: 0.05 },
    { id: 57, marital_status: 1, children_number: 1, expense_revenue_item_id: 20, expense_ratio_to_revenue: 0.05 },

    # 配偶者あり、子ども2人
    { id: 58, marital_status: 1, children_number: 2, expense_revenue_item_id: 2, expense_ratio_to_revenue: 0.25 },
    { id: 59, marital_status: 1, children_number: 2, expense_revenue_item_id: 3, expense_ratio_to_revenue: 0.01 },
    { id: 60, marital_status: 1, children_number: 2, expense_revenue_item_id: 4, expense_ratio_to_revenue: 0.01 },
    { id: 61, marital_status: 1, children_number: 2, expense_revenue_item_id: 5, expense_ratio_to_revenue: 0.01 },
    { id: 62, marital_status: 1, children_number: 2, expense_revenue_item_id: 6, expense_ratio_to_revenue: 0.01 },
    { id: 63, marital_status: 1, children_number: 2, expense_revenue_item_id: 7, expense_ratio_to_revenue: 0.1 },
    { id: 64, marital_status: 1, children_number: 2, expense_revenue_item_id: 8, expense_ratio_to_revenue: 0.015 },
    { id: 65, marital_status: 1, children_number: 2, expense_revenue_item_id: 9, expense_ratio_to_revenue: 0.25 },
    { id: 66, marital_status: 1, children_number: 2, expense_revenue_item_id: 10, expense_ratio_to_revenue: 0.015 },
    { id: 67, marital_status: 1, children_number: 2, expense_revenue_item_id: 11, expense_ratio_to_revenue: 0.015 },
    { id: 68, marital_status: 1, children_number: 2, expense_revenue_item_id: 12, expense_ratio_to_revenue: 0.01 },
    { id: 69, marital_status: 1, children_number: 2, expense_revenue_item_id: 13, expense_ratio_to_revenue: 0.01 },
    { id: 70, marital_status: 1, children_number: 2, expense_revenue_item_id: 14, expense_ratio_to_revenue: 0.03 },
    { id: 71, marital_status: 1, children_number: 2, expense_revenue_item_id: 15, expense_ratio_to_revenue: 0.03 },
    { id: 72, marital_status: 1, children_number: 2, expense_revenue_item_id: 16, expense_ratio_to_revenue: 0.05 },
    { id: 73, marital_status: 1, children_number: 2, expense_revenue_item_id: 17, expense_ratio_to_revenue: 0.03 },
    { id: 74, marital_status: 1, children_number: 2, expense_revenue_item_id: 18, expense_ratio_to_revenue: 0.05 },
    { id: 75, marital_status: 1, children_number: 2, expense_revenue_item_id: 19, expense_ratio_to_revenue: 0.05 },
    { id: 76, marital_status: 1, children_number: 2, expense_revenue_item_id: 20, expense_ratio_to_revenue: 0.05 },

)
